// @generated by tools/i18n/catalog.py; edit locales/en.json or locales/en/*.json.
// Stable IDs/parameters are machine data; patterns are human presentation only.
use super::{Definition, Parameter, ParameterKind};
#[rustfmt::skip]
pub(super) static MESSAGES: &[Definition] = &[
    Definition {
        id: r#"cli.archive.ok"#,
        context: r#"Successful archive integrity check."#,
        parameters: &[
        ],
        other: r#"archive OK"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.block.limit"#,
        context: r#"Warning when requested frame size is clamped. CIXG1 and numeric limits are invariant technical facts."#,
        parameters: &[
        ],
        other: r#"cix: CIXG1 limits frames to 65536 bytes; effective block size is 65536 bytes"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.error"#,
        context: r#"Top-level error wrapper. The detail may still be untranslated legacy/system text; the wrapper alone does not constitute complete diagnostic coverage."#,
        parameters: &[
            Parameter { name: r#"detail"#, kind: ParameterKind::Text },
        ],
        other: r#"cix: {detail}"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.file.error"#,
        context: r#"Error for a named input. Preserve path bytes in I/O; isolate direction only in display. Legacy detail is tracked separately."#,
        parameters: &[
            Parameter { name: r#"detail"#, kind: ParameterKind::Text },
            Parameter { name: r#"path"#, kind: ParameterKind::Path },
        ],
        other: r#"cix: {path}: {detail}"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.files.failed"#,
        context: r#"Multi-file failure summary. Plural category follows the total number of input files, not the number of failures."#,
        parameters: &[
            Parameter { name: r#"failures"#, kind: ParameterKind::Number },
            Parameter { name: r#"total"#, kind: ParameterKind::Number },
        ],
        other: r#"{failures} of {total} input files failed"#,
        one: Some(r#"{failures} of {total} input file failed"#),
        plural: Some(r#"total"#),
    },
    Definition {
        id: r#"cli.help.advanced"#,
        context: r#"CLI help heading for expert options."#,
        parameters: &[
        ],
        other: r#"Advanced / expert controls (usually unnecessary):"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.best"#,
        context: r#"BEST effort help paragraph; preserve options and wire format identifiers."#,
        parameters: &[
        ],
        other: r#"
BEST compares complete compatible native containers and native-library backend archives within --memory. Ordinary stdin, non-regular and oversized inputs use bounded independent CIXW1 windows when their controls permit it; --stream, history and flush controls retain the framed encoder. Expert controls constrain their specified dimensions. Use --verbose or --explain for evaluated candidates and resource exclusions."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.effort"#,
        context: r#"CLI --help paragraph. Preserve literal CLI commands/options, container names and numeric defaults; translate prose."#,
        parameters: &[
        ],
        other: r#"Effort: --fast minimises compression latency; no option is balanced automatic selection; --best searches aggressively for smaller output. Numeric aliases: -1 fast, -6 default, -9 best."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.files"#,
        context: r#"CLI --help paragraph. Preserve literal CLI commands/options, container names and numeric defaults; translate prose."#,
        parameters: &[
        ],
        other: r#"FILE defaults to '-' (standard input); use '--' before a dash-prefixed filename. Input files are kept by default. Use '-' for standard input or output. Multiple named files receive their own derived output names; -o FILE and standard-output modes accept one input only. CIX archives are CIX streams, not ZIP or gzip. Tar pipelines support directories."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.observability"#,
        context: r#"CLI --help paragraph. Preserve literal CLI commands/options, container names and numeric defaults; translate prose."#,
        parameters: &[
        ],
        other: r#"Observability: --explain reports per-block candidate costs and decisions; --verbose reports aggregate search statistics."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.backend"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Override nested substream backend"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.block_size"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Constrain maximum uncompressed block size"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.external"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Explicitly wrap a direct external codec (CIXB1)"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.flush_interval"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Flush framed partial blocks after idle time"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.format"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Select or constrain the container version"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.history"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Request retained history"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.independent_blocks"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Request model reset boundaries"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.memory"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Bound accounted working memory (FAST/default 512 MiB; BEST/decode 6 GiB)"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.parallelism"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Choose ordered blocks or within-block trials"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.portfolio"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Compare CIX and direct external candidates (CIXB1)"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.profile"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Select external profile or native effort"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.route"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Override route selection"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.stream"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Require streaming operation"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.option.threads"#,
        context: r#"CLI option and description. The option argument is invariant syntax, never translate it."#,
        parameters: &[
            Parameter { name: r#"option"#, kind: ParameterKind::Code },
        ],
        other: r#"  {option}
      Bound CPU workers (1..20; default up to 4)"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.providers"#,
        context: r#"CLI provider location help; preserve CLI option spellings and PATH."#,
        parameters: &[
        ],
        other: r#"
Installed full-engine providers: --private-library-dir names an absolute private CIX provider directory; --temporary-root names an absolute private PAQ worker root. Provider files are never searched through PATH."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.standard"#,
        context: r#"CLI standard-format help paragraph; preserve option spellings and format IDs."#,
        parameters: &[
        ],
        other: r#"
Standard streams: --output-format gzip|zlib|deflate|bzip2|xz|zstd|brotli|lz4|snappy writes a genuine one-shot standard stream. Use --input-format FORMAT with -d, -t or uncix to decode/test it; raw Deflate is never guessed. Standard streams are bounded to 128 MiB input/output and do not accept CIX route, container, portfolio, stream, history or block controls."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.title"#,
        context: r#"CLI --help paragraph. Preserve literal CLI commands/options, container names and numeric defaults; translate prose."#,
        parameters: &[
        ],
        other: r#"CIX (pronounced six) — automatic lossless stream compression"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.help.usage"#,
        context: r#"CLI --help paragraph. Preserve literal CLI commands/options, container names and numeric defaults; translate prose."#,
        parameters: &[
        ],
        other: r#"Usage: cix [--fast|--best] [-c] [-k] [-f] [-o FILE] [FILE ...]
       uncix [-c] [-k] [-f] [-t|-l] [-o FILE] [FILE ...]
       cixcat [FILE]"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.interrupt.install"#,
        context: r#"Failure installing the executable signal handler. OS detail is separately attributed."#,
        parameters: &[
            Parameter { name: r#"detail"#, kind: ParameterKind::Text },
        ],
        other: r#"cix: could not install interrupt handler: {detail}"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"cli.output.path"#,
        context: r#"Output path display only. The actual filesystem path is never translated or normalized."#,
        parameters: &[
            Parameter { name: r#"path"#, kind: ParameterKind::Path },
        ],
        other: r#"{path}"#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"managed.error.forbidden"#,
        context: r#"Managed SDK authorization denied; do not imply a grant or expose credentials."#,
        parameters: &[
        ],
        other: r#"Permission denied."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"managed.error.internal"#,
        context: r#"Managed SDK internal failure; raw causes and sensitive details are intentionally omitted."#,
        parameters: &[
        ],
        other: r#"Internal error."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"managed.error.invalid_argument"#,
        context: r#"Managed SDK request rejection; field is an invariant request field identifier."#,
        parameters: &[
            Parameter { name: r#"field"#, kind: ParameterKind::Code },
        ],
        other: r#"Invalid request field: {field}."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"managed.error.invalid_configuration"#,
        context: r#"Managed SDK configuration rejection; field is an invariant field identifier, never a secret or translated value."#,
        parameters: &[
            Parameter { name: r#"field"#, kind: ParameterKind::Code },
        ],
        other: r#"Invalid configuration field: {field}."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"managed.error.resource_limit"#,
        context: r#"Managed SDK resource cap rejection; resource is an invariant cap identifier, not a translated resource name."#,
        parameters: &[
            Parameter { name: r#"resource"#, kind: ParameterKind::Code },
        ],
        other: r#"Resource limit exceeded: {resource}."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"managed.error.session_expired"#,
        context: r#"Managed SDK session is no longer valid; no automatic renewal is implied."#,
        parameters: &[
        ],
        other: r#"Session expired."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"service.error.internal"#,
        context: r#"Core service internal failure; raw causes and sensitive details are intentionally omitted."#,
        parameters: &[
        ],
        other: r#"Internal error."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"service.error.invalid_argument"#,
        context: r#"Core service request rejection; field is an invariant field identifier, inserted literally and never translated."#,
        parameters: &[
            Parameter { name: r#"field"#, kind: ParameterKind::Code },
        ],
        other: r#"Invalid request field: {field}."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"service.error.metadata_unavailable"#,
        context: r#"Core service metadata database failure; do not expose queries or promise recovery or automatic retries."#,
        parameters: &[
        ],
        other: r#"Metadata is unavailable."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"service.error.not_found"#,
        context: r#"Core service requested resource is absent; do not expose resource identifiers or infer authorization."#,
        parameters: &[
        ],
        other: r#"Resource not found."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"service.error.resource_limit"#,
        context: r#"Core service resource cap rejection; resource is an invariant resource identifier, inserted literally and never translated."#,
        parameters: &[
            Parameter { name: r#"resource"#, kind: ParameterKind::Code },
        ],
        other: r#"Resource limit exceeded: {resource}."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"service.error.revision_conflict"#,
        context: r#"Core service revision or uniqueness conflict; no automatic retry or overwrite is implied."#,
        parameters: &[
        ],
        other: r#"Revision conflict."#,
        one: None,
        plural: None,
    },
    Definition {
        id: r#"service.error.storage_io"#,
        context: r#"Core service storage I/O failure; do not expose paths or promise recovery or automatic retries."#,
        parameters: &[
        ],
        other: r#"Storage is unavailable."#,
        one: None,
        plural: None,
    },
];
